---
driver:
  name: vagrant
  gui: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
  - name: windows-10
    driver:
      box: inclusivedesign/windows10-eval

suites:
  - name: default
    run_list:
      - recipe[nuget_test::sources]
