---
driver:
  name: vagrant
  gui: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  # - name: windows-10
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: default
    run_list:
      - recipe[nuget::default]
      - recipe[nuget_test::default]
    attributes:
      nuget:
        repositories:
          name1: http://example.com/name1
          name2: http://example.com/name2
