---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2

suites:
  - name: default
    run_list:
      - recipe[nuget::default]
      - recipe[nuget_test::default]
    attributes:
      nuget:
        repositories:
          name1: http://example.com/name1
          name2: http://example.com/name2
